server:
 port: 8081

spring:
 autoconfigure:
  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
 data:
  mongodb:
   uri: mongodb+srv://testUser:testpassword@trading.ufeml.mongodb.net/Trading?retryWrites=true&w=majority
   database: Trading

# jwt:
#  secret: secretKey